### ISSUE TITLE
Issue with yt_dlp

### ISSUE THREAD

**Issue by ilaria-manco** [seungheondoh/music_caps_dl#1]
There's an issue with version `2023.1.6` of `yt_dlp`, which gives an `Unable to extract uploader id` error.

This is due to a change in the YouTube metadata (see [this issue](https://github.com/ytdl-org/youtube-dl/issues/31530#Description)).

Upgrading to `2023.03.04` solves the issue.

**Comment by seungheondoh** [comment]
Thanks for update!
